<?php

/**
 * @file
 * Install, update, and uninstall functions for the WP Migrate module.
 */

/**
 * Implements hook_uninstall().
 *
 * Cleans up config entities installed by this module.
 */
function migrate_wordpress_uninstall() {
  db_query("DELETE FROM {config} WHERE name LIKE '%wp_%'");
  db_query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration_group.wordpress%'");
  \Drupal::cache()->deleteAll();
}
